# -*- coding: utf-8 -*-
"""AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11NlIcSTc7Fj-972QtefjgK0LDJ_6ODt6
"""

# Commented out IPython magic to ensure Python compatibility.
# Install PyTorch, Torchvision, PIL, Matplotlib, and the YOLOv5 repo
!pip install --quiet torch torchvision pillow matplotlib
!git clone --quiet https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
!pip install --quiet -r requirements.txt

import torch
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np

# Load the pretrained YOLOv5s model directly via torch.hub
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)
model.eval()  # set to inference mode
names = model.names  # class names

print(f"✅ Loaded YOLOv5s with {len(names)} classes")

from google.colab import files

uploaded = files.upload()
# This will prompt you to upload one or more image files.
# We'll pick the first one:
img_path = list(uploaded.keys())[0]
print(f"🖼️ Uploaded: {img_path}")

# Load image
from PIL import Image # Import Image class here
img = Image.open(img_path)

# Run inference
results = model(img)

# Show results
results.show()  # Display image with boxes

# If you want to save:
# results.save(save_dir='runs/detect/exp')

# ✅ STEP 1: ZIP the entire content folder
!zip -r project_backup.zip /content

# ✅ STEP 2: Download the ZIP file
from google.colab import files
files.download('project_backup.zip')